services:
  - type: web
    name: project1-flask
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn flask_api:app --bind 0.0.0.0:$PORT

services:
  - type: web
    name: iris-streamlit-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT --server.address=0.0.0.0 --server.enableCORS=false
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
